### DISCUSSION TITLE
Full Screen view for small displays

### DISCUSSION THREAD

**Discussion by mailrahulboora** [OpenBoard-org/OpenBoard#1207] [Q&A] [answered]
![Screenshot_1](https://github.com/user-attachments/assets/267d1075-68b2-4ba8-8e45-83b074438014)

Is it possible to anyhow minimize the thickness of top bar to as minimum as possible. 
i use this for online teaching and this upper setting ribbon takes lot of teaching area. on small screen its very important to have max teaching/writing area. to any method to remove it 
and also how to change background color to some different color(dark green - less effect on eyes ). any help would be appreciated

**Comment by letsfindaway** [comment, marked as answer]
You can a little bit squeeze the top toolbar by the following actions:

- First go to preferences and uncheck the "Display text under button" checkbox. 
![grafik](https://github.com/user-attachments/assets/3fcb1826-0630-43db-abda-f5e9a9eb8f70)

- This does not affect the height of the toolbar, so we have to do another step. This depends on the platform you're using.
- Locate the `OpenBoard.css` file in your installation. It should be in some `etc` directory within the installation path. Here edit and change the toolbar properties as shown in the following snippet, starting at about line 88 in this file:
```css
QToolBar QToolButton
{

    margin: 0px;   <-- change this value
    margin-left: 0px;
    margin-right: 0px;
    padding: 0px;
    border: none;
    height: 28px;   <-- change this value
}

QToolBar QToolButton:pressed
{
    margin: 0px;   <-- change this value
    margin-left: 0px;
    margin-right: 0px;
    padding: 0px;
    border: none;
    height: 28px;   <-- change this value

    background: qradialgradient(cx:0.5, cy:0.5, radius: 0.5,
                 fx:0.5, fy:0.5, stop: 0 #d3d3d3, stop: 1  #b3b3b3);
}

```

You will then get a much smaller menu bar at the top:
![grafik](https://github.com/user-attachments/assets/807450b9-f916-4e6f-b35c-68b78d361d57)

For your second question: Changing the black background is already discussed, but I cannot tell you when it will be implemented.
